# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-26 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='command',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cronjob',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='name',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
    ]
